export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="$PATH:/opt/homebrew/lib/ruby/gems/3.4.0/bin"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"
